Program = _{ SOI ~ Stmt* ~ EOF }

Stmt = { Let | Assign | Expr }

Let = { LetKw ~ Ident ~ "=" ~ Expr }

LetKw = @{ "let" ~ !IdentChar }

IdentChar = _{ ASCII_ALPHANUMERIC | "_" }

Ident = @{ (ASCII_ALPHA | "_") ~ IdentChar* }

Assign = { Ident ~ "=" ~ Expr }

Expr = { AddSub }

AddSub = { MulDiv ~ (AddOp ~ MulDiv)* }

MulDiv = { UnaryExpr ~ (MulOp ~ UnaryExpr)* }

UnaryExpr = { UnaryOp? ~ Term }

Term = { Ident | Int | "(" ~ Expr ~ ")" }

AddOp = { "+" | "-" }

MulOp = { "*" | "/" }

UnaryOp = { "+" | "-" }

BinaryExpr = { (UnaryExpr | Term) ~ (Operator ~ Term)+ }

Operator = { "+" | "-" }

Int = @{ ASCII_DIGIT+ }

WHITESPACE = _{ " " | "\t" | "\r" | "\n" } 

EOF = _{ EOI | ";" }

//omfg i have no idea what this file is about 
// i mean i do know what it does
// but yk so weird
// weird right?
