Program = _{ SOI ~ Expr ~ EOF }

Expr = { AddSub }

AddSub = { MulDiv ~ (AddOp ~ MulDiv)* }

MulDiv = { UnaryExpr ~ (MulOp ~ UnaryExpr)* }


UnaryExpr = { UnaryOp? ~ Term }

Term = { Int | "(" ~ Expr ~ ")" }

AddOp = { "+" | "-" }

BinaryExpr = { (UnaryExpr | Term) ~ (Operator ~ Term)+ }

Operator = { "+" | "-" }

Int = @{ ASCII_DIGIT+ }

WHITESPACE = _{ " " | "\t" | "\r" | "\n" } 

EOF = _{ EOI | ";" }